/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pingan_one_framework_demo_plugin_Math */

#ifndef _Included_com_pingan_one_framework_demo_plugin_Math
#define _Included_com_pingan_one_framework_demo_plugin_Math
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pingan_one_framework_demo_plugin_Math
 * Method:    plus
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_com_pingan_one_framework_demo_plugin_Math_plus
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
